//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.18444
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WindowsFormsApplication1.ErdoganTheMaster {
    using System.Runtime.Serialization;
    using System;
    
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.CollectionDataContractAttribute(Name="ArrayOfString", Namespace="http://SuperErdogan.org/", ItemName="string")]
    [System.SerializableAttribute()]
    public class ArrayOfString : System.Collections.Generic.List<string> {
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(Namespace="http://SuperErdogan.org/", ConfigurationName="ErdoganTheMaster.WebServiceSoap")]
    public interface WebServiceSoap {
        
        // CODEGEN: Generating message contract since element name filename from namespace http://SuperErdogan.org/ is not marked nillable
        [System.ServiceModel.OperationContractAttribute(Action="http://SuperErdogan.org/getTxtFile", ReplyAction="*")]
        WindowsFormsApplication1.ErdoganTheMaster.getTxtFileResponse getTxtFile(WindowsFormsApplication1.ErdoganTheMaster.getTxtFileRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://SuperErdogan.org/getTxtFile", ReplyAction="*")]
        System.Threading.Tasks.Task<WindowsFormsApplication1.ErdoganTheMaster.getTxtFileResponse> getTxtFileAsync(WindowsFormsApplication1.ErdoganTheMaster.getTxtFileRequest request);
        
        // CODEGEN: Generating message contract since element name getAllFileNamesResult from namespace http://SuperErdogan.org/ is not marked nillable
        [System.ServiceModel.OperationContractAttribute(Action="http://SuperErdogan.org/getAllFileNames", ReplyAction="*")]
        WindowsFormsApplication1.ErdoganTheMaster.getAllFileNamesResponse getAllFileNames(WindowsFormsApplication1.ErdoganTheMaster.getAllFileNamesRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://SuperErdogan.org/getAllFileNames", ReplyAction="*")]
        System.Threading.Tasks.Task<WindowsFormsApplication1.ErdoganTheMaster.getAllFileNamesResponse> getAllFileNamesAsync(WindowsFormsApplication1.ErdoganTheMaster.getAllFileNamesRequest request);
        
        // CODEGEN: Generating message contract since element name fileText from namespace http://SuperErdogan.org/ is not marked nillable
        [System.ServiceModel.OperationContractAttribute(Action="http://SuperErdogan.org/ChangeTxtFile", ReplyAction="*")]
        WindowsFormsApplication1.ErdoganTheMaster.ChangeTxtFileResponse ChangeTxtFile(WindowsFormsApplication1.ErdoganTheMaster.ChangeTxtFileRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://SuperErdogan.org/ChangeTxtFile", ReplyAction="*")]
        System.Threading.Tasks.Task<WindowsFormsApplication1.ErdoganTheMaster.ChangeTxtFileResponse> ChangeTxtFileAsync(WindowsFormsApplication1.ErdoganTheMaster.ChangeTxtFileRequest request);
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class getTxtFileRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="getTxtFile", Namespace="http://SuperErdogan.org/", Order=0)]
        public WindowsFormsApplication1.ErdoganTheMaster.getTxtFileRequestBody Body;
        
        public getTxtFileRequest() {
        }
        
        public getTxtFileRequest(WindowsFormsApplication1.ErdoganTheMaster.getTxtFileRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://SuperErdogan.org/")]
    public partial class getTxtFileRequestBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string filename;
        
        public getTxtFileRequestBody() {
        }
        
        public getTxtFileRequestBody(string filename) {
            this.filename = filename;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class getTxtFileResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="getTxtFileResponse", Namespace="http://SuperErdogan.org/", Order=0)]
        public WindowsFormsApplication1.ErdoganTheMaster.getTxtFileResponseBody Body;
        
        public getTxtFileResponse() {
        }
        
        public getTxtFileResponse(WindowsFormsApplication1.ErdoganTheMaster.getTxtFileResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://SuperErdogan.org/")]
    public partial class getTxtFileResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string getTxtFileResult;
        
        public getTxtFileResponseBody() {
        }
        
        public getTxtFileResponseBody(string getTxtFileResult) {
            this.getTxtFileResult = getTxtFileResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class getAllFileNamesRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="getAllFileNames", Namespace="http://SuperErdogan.org/", Order=0)]
        public WindowsFormsApplication1.ErdoganTheMaster.getAllFileNamesRequestBody Body;
        
        public getAllFileNamesRequest() {
        }
        
        public getAllFileNamesRequest(WindowsFormsApplication1.ErdoganTheMaster.getAllFileNamesRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute()]
    public partial class getAllFileNamesRequestBody {
        
        public getAllFileNamesRequestBody() {
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class getAllFileNamesResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="getAllFileNamesResponse", Namespace="http://SuperErdogan.org/", Order=0)]
        public WindowsFormsApplication1.ErdoganTheMaster.getAllFileNamesResponseBody Body;
        
        public getAllFileNamesResponse() {
        }
        
        public getAllFileNamesResponse(WindowsFormsApplication1.ErdoganTheMaster.getAllFileNamesResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://SuperErdogan.org/")]
    public partial class getAllFileNamesResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public WindowsFormsApplication1.ErdoganTheMaster.ArrayOfString getAllFileNamesResult;
        
        public getAllFileNamesResponseBody() {
        }
        
        public getAllFileNamesResponseBody(WindowsFormsApplication1.ErdoganTheMaster.ArrayOfString getAllFileNamesResult) {
            this.getAllFileNamesResult = getAllFileNamesResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class ChangeTxtFileRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="ChangeTxtFile", Namespace="http://SuperErdogan.org/", Order=0)]
        public WindowsFormsApplication1.ErdoganTheMaster.ChangeTxtFileRequestBody Body;
        
        public ChangeTxtFileRequest() {
        }
        
        public ChangeTxtFileRequest(WindowsFormsApplication1.ErdoganTheMaster.ChangeTxtFileRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://SuperErdogan.org/")]
    public partial class ChangeTxtFileRequestBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string fileText;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=1)]
        public string filename;
        
        public ChangeTxtFileRequestBody() {
        }
        
        public ChangeTxtFileRequestBody(string fileText, string filename) {
            this.fileText = fileText;
            this.filename = filename;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class ChangeTxtFileResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="ChangeTxtFileResponse", Namespace="http://SuperErdogan.org/", Order=0)]
        public WindowsFormsApplication1.ErdoganTheMaster.ChangeTxtFileResponseBody Body;
        
        public ChangeTxtFileResponse() {
        }
        
        public ChangeTxtFileResponse(WindowsFormsApplication1.ErdoganTheMaster.ChangeTxtFileResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute()]
    public partial class ChangeTxtFileResponseBody {
        
        public ChangeTxtFileResponseBody() {
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface WebServiceSoapChannel : WindowsFormsApplication1.ErdoganTheMaster.WebServiceSoap, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class WebServiceSoapClient : System.ServiceModel.ClientBase<WindowsFormsApplication1.ErdoganTheMaster.WebServiceSoap>, WindowsFormsApplication1.ErdoganTheMaster.WebServiceSoap {
        
        public WebServiceSoapClient() {
        }
        
        public WebServiceSoapClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public WebServiceSoapClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public WebServiceSoapClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public WebServiceSoapClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        WindowsFormsApplication1.ErdoganTheMaster.getTxtFileResponse WindowsFormsApplication1.ErdoganTheMaster.WebServiceSoap.getTxtFile(WindowsFormsApplication1.ErdoganTheMaster.getTxtFileRequest request) {
            return base.Channel.getTxtFile(request);
        }
        
        public string getTxtFile(string filename) {
            WindowsFormsApplication1.ErdoganTheMaster.getTxtFileRequest inValue = new WindowsFormsApplication1.ErdoganTheMaster.getTxtFileRequest();
            inValue.Body = new WindowsFormsApplication1.ErdoganTheMaster.getTxtFileRequestBody();
            inValue.Body.filename = filename;
            WindowsFormsApplication1.ErdoganTheMaster.getTxtFileResponse retVal = ((WindowsFormsApplication1.ErdoganTheMaster.WebServiceSoap)(this)).getTxtFile(inValue);
            return retVal.Body.getTxtFileResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<WindowsFormsApplication1.ErdoganTheMaster.getTxtFileResponse> WindowsFormsApplication1.ErdoganTheMaster.WebServiceSoap.getTxtFileAsync(WindowsFormsApplication1.ErdoganTheMaster.getTxtFileRequest request) {
            return base.Channel.getTxtFileAsync(request);
        }
        
        public System.Threading.Tasks.Task<WindowsFormsApplication1.ErdoganTheMaster.getTxtFileResponse> getTxtFileAsync(string filename) {
            WindowsFormsApplication1.ErdoganTheMaster.getTxtFileRequest inValue = new WindowsFormsApplication1.ErdoganTheMaster.getTxtFileRequest();
            inValue.Body = new WindowsFormsApplication1.ErdoganTheMaster.getTxtFileRequestBody();
            inValue.Body.filename = filename;
            return ((WindowsFormsApplication1.ErdoganTheMaster.WebServiceSoap)(this)).getTxtFileAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        WindowsFormsApplication1.ErdoganTheMaster.getAllFileNamesResponse WindowsFormsApplication1.ErdoganTheMaster.WebServiceSoap.getAllFileNames(WindowsFormsApplication1.ErdoganTheMaster.getAllFileNamesRequest request) {
            return base.Channel.getAllFileNames(request);
        }
        
        public WindowsFormsApplication1.ErdoganTheMaster.ArrayOfString getAllFileNames() {
            WindowsFormsApplication1.ErdoganTheMaster.getAllFileNamesRequest inValue = new WindowsFormsApplication1.ErdoganTheMaster.getAllFileNamesRequest();
            inValue.Body = new WindowsFormsApplication1.ErdoganTheMaster.getAllFileNamesRequestBody();
            WindowsFormsApplication1.ErdoganTheMaster.getAllFileNamesResponse retVal = ((WindowsFormsApplication1.ErdoganTheMaster.WebServiceSoap)(this)).getAllFileNames(inValue);
            return retVal.Body.getAllFileNamesResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<WindowsFormsApplication1.ErdoganTheMaster.getAllFileNamesResponse> WindowsFormsApplication1.ErdoganTheMaster.WebServiceSoap.getAllFileNamesAsync(WindowsFormsApplication1.ErdoganTheMaster.getAllFileNamesRequest request) {
            return base.Channel.getAllFileNamesAsync(request);
        }
        
        public System.Threading.Tasks.Task<WindowsFormsApplication1.ErdoganTheMaster.getAllFileNamesResponse> getAllFileNamesAsync() {
            WindowsFormsApplication1.ErdoganTheMaster.getAllFileNamesRequest inValue = new WindowsFormsApplication1.ErdoganTheMaster.getAllFileNamesRequest();
            inValue.Body = new WindowsFormsApplication1.ErdoganTheMaster.getAllFileNamesRequestBody();
            return ((WindowsFormsApplication1.ErdoganTheMaster.WebServiceSoap)(this)).getAllFileNamesAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        WindowsFormsApplication1.ErdoganTheMaster.ChangeTxtFileResponse WindowsFormsApplication1.ErdoganTheMaster.WebServiceSoap.ChangeTxtFile(WindowsFormsApplication1.ErdoganTheMaster.ChangeTxtFileRequest request) {
            return base.Channel.ChangeTxtFile(request);
        }
        
        public void ChangeTxtFile(string fileText, string filename) {
            WindowsFormsApplication1.ErdoganTheMaster.ChangeTxtFileRequest inValue = new WindowsFormsApplication1.ErdoganTheMaster.ChangeTxtFileRequest();
            inValue.Body = new WindowsFormsApplication1.ErdoganTheMaster.ChangeTxtFileRequestBody();
            inValue.Body.fileText = fileText;
            inValue.Body.filename = filename;
            WindowsFormsApplication1.ErdoganTheMaster.ChangeTxtFileResponse retVal = ((WindowsFormsApplication1.ErdoganTheMaster.WebServiceSoap)(this)).ChangeTxtFile(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<WindowsFormsApplication1.ErdoganTheMaster.ChangeTxtFileResponse> WindowsFormsApplication1.ErdoganTheMaster.WebServiceSoap.ChangeTxtFileAsync(WindowsFormsApplication1.ErdoganTheMaster.ChangeTxtFileRequest request) {
            return base.Channel.ChangeTxtFileAsync(request);
        }
        
        public System.Threading.Tasks.Task<WindowsFormsApplication1.ErdoganTheMaster.ChangeTxtFileResponse> ChangeTxtFileAsync(string fileText, string filename) {
            WindowsFormsApplication1.ErdoganTheMaster.ChangeTxtFileRequest inValue = new WindowsFormsApplication1.ErdoganTheMaster.ChangeTxtFileRequest();
            inValue.Body = new WindowsFormsApplication1.ErdoganTheMaster.ChangeTxtFileRequestBody();
            inValue.Body.fileText = fileText;
            inValue.Body.filename = filename;
            return ((WindowsFormsApplication1.ErdoganTheMaster.WebServiceSoap)(this)).ChangeTxtFileAsync(inValue);
        }
    }
}
